feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

from django.conf.urls import include

from feed import urls as feed_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField


# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()
    
    def __str__(self):
        return self.text

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()
    

feed/views.py
# from django.shortcuts import render    ### this is for a function-based view
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from urllib import request

from .forms import PostForm
from .models import Post

class HomePageView(TemplateView):
    template_name = "home.html"

# Create your views here.


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["my_thing"] = "Hello world. This is dynamic"
        context["posts"] = Post.objects.all().order_by('-id')
        return context
        

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post


class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
        

    def form_valid(self, form):
        # Create a new post:
        new_object = Post.objects.create(
            text=form.cleaned_data['text'], 
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful!')

        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%  block title  %}Default Title{%  endblock  %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @tailwind base;
        @tailwind components;
        @tailwind utilities;
    </style>

</head>
<body class="px-3">
    {% block nav %}{% include 'includes/navbar.html' %}{% endblock nav %}
    {% if messages %}
    <ul class="messages text-white float-right bg-gray-600 px-4 py-2 mr-3">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }} &nbsp;
            <svg class="h-6 w-6 fill-sky-100 stroke-sky-500 stroke-2 float-right" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="11"></circle>
            <path d="m8 13 2.165 2.165a1 1 0 0 0 1.521-.126L16 9" fill="none"></path>
          </svg></li>
        {% endfor %}
    </ul>
    {% endif %}


    {%  block body  %}{%  endblock %}

<script src="https://flowbite.com/docs/flowbite.min.js?v=1.6.6a"></script>

</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title%}Detail View{% endblock %}

{%  block body  %}

<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 overflow-hidden">
    <img src="/media/{{ object.image }}" alt="{{ object.text }}" />
    <div class="p-5">
        <a href="#">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"> {{ object.text }} </h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
        <a href="{% url 'feed:index' %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            &larr; Go Back
        </a>
    </div>
</div>


{% endblock %}

templates/home.html
{%  extends "base.html"  %}
{%  load thumbnail  %}

{%  block title  %}homepage{%  endblock  %}



{%  block body  %}

<a href="{% url 'feed:post' %}" class="border mx-auto px-2 rounded-md ml-3">Add a new post &rarr;</a>
<div class="grid gap-4 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
    {% for post in posts %}
        <a href="{% url 'feed:detail' post.id %}" class='p-6 bg-white w-full block'>
            <div class='bg-gray-50 shadow-lg border rounded-md my-4'>
                <div class='mx-auto py-4 px-6 flex-col lg:items-center lg:py-8 lg:px-8'>

                    {% thumbnail post.image "100x100" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% endthumbnail %}

                    <h3>{{ post.text }}</h3>
                </div>
            </div>
        </a>
    {% endfor %}
</div>

{%  endblock  %}

templates/includes/navbar.html
<nav class="bg-white border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <a href="https://flowbite.com/" class="flex items-center">
          <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 mr-3" alt="Flowbite Logo" />
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
      </a>
      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <a href="{% url 'feed:index' %}" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" aria-current="page">Home</a>
          </li>
          <li>
            <a href="{% url 'feed:index' %}" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
          </li>
          <li>
            <a href="{% url 'feed:post' %}" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Add New Post</a>
          </li>
          <li>
            <a href="{% url 'feed:index' %}" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Pricing</a>
          </li>
          <li>
            <a href="{% url 'feed:index' %}" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

templates/new_post.html
{%  extends "base.html"  %}

{%  block title  %}Upload a New Image{%  endblock  %}

{%  block body  %}
<form method="POST" action="" enctype="multipart/form-data" class='h-full py-6 px-6 bg-white'>
    <div class='bg-gray-200 shadow-lg border rounded-md'>
        <div class='mx-auto max-w-7xl py-12 px-6 lg:flex lg:items-center lg:justify-between lg:py-16 lg:px-8'>
        {% csrf_token %}
        {{ form.as_p}}
        <div class="mt-4">
            <button type="submit" class="bg-gray-50 shadow-md px-2 rounded-md">Submit form</button>
        </div>
    </div>
</div>
{%  endblock  %}